services:
  postgres:
    image: postgres:17
    container_name: aisi-postgres
    environment:
      POSTGRES_DB: netflix
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: app@123
    ports:
      - "5432:5432"
    volumes:
      - aisi-pgdata:/var/lib/postgresql/data

volumes:
  aisi-pgdata:
