server.port=9090
spring.application.name=jwt-auth-demo
spring.profiles.active=development


spring.datasource.url=jdbc:postgresql://localhost:5432/netflix
spring.datasource.username=appuser
spring.datasource.password=app@123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=never


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true


jwt.header=Authorization
jwt.token.type=Bearer
jwt.issuer=http://localhost:9090/auth/login
jwt.expiration-ms=900000
jwt.refresh-token.expiration-ms=1296000000
jwt.key-algorithm=HMAC
jwt.key-secret=a-string-secret-at-least-256-bits-long
jwt.public-key-file=./src/main/resources/publicKey.pem
jwt.private-key-file=./src/main/resources/privateKey.pem
jwt.keySize=2048
jwt.cookie.name=accessToken
jwt.cookie.path=/api
jwt.cookie.max-age-ms=86400000
jwt.cookie.secure=true
jwt.cookie.http-only=true
jwt.cookie.same-site=Lax
jwt.cookie.response-enabled=true


cors-allowed-origins=http://localhost:8082,http://localhost:8083
cors-allowed-methods=GET,POST,PUT,DELETE,OPTIONS
cors-allowed-headers=Authorization,Cache-Control,Content-Type
cors-exposed-headers=Authorization,Content-Length
cors-configuration-endpoint=/**
cors-allow-credentials=true
cors-max-age=3600


permit-all-request-url=/auth/**
excluded-paths-for-authentication=/auth/login,/auth/refresh-token

backup.directory=./backups
backup.container-name=aisi-postgres
backup.database-name=netflix