{
 "title": "AISI Camel Routes",
 "tags": [
  "camel",
  "aisi"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Exchanges processed (total)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(camel_exchanges_total)" }
   ]
  },
  {
   "title": "Exchanges succeeded (total)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(camel_exchanges_succeeded_total)"
    }
   ]
  },
  {
   "title": "Exchanges failed (total)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(camel_exchanges_failed_total)"
    }
   ]
  },
  {
   "title": "Routes running",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "count(count by (routeId) (camel_exchanges_total))"
    }
   ]
  },
  {
   "title": "Camel exchanges processed (rate / sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(camel_exchanges_succeeded_total[1m])) by (routeId)",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Camel exchange failures (rate / sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(camel_exchanges_failed_total[1m])) by (routeId)",
     "legendFormat": "{{routeId}}"
    }
   ]
  }
 ]
}