spring.application.name=aisi-camel-routes
server.port=8085


camel.springboot.main-run-controller=true
camel.springboot.name=NetflixApiCamelContext
camel.springboot.stream-caching-enabled=true


management.endpoint.health.show-details=always

logging.level.hr.algebra=DEBUG
logging.level.org.apache.camel=INFO

spring.jackson.serialization.indent-output=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

camel.component.kafka.brokers=localhost:9094

management.endpoints.web.exposure.include=health,info,metrics,prometheus,camelroutes
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=aisi-camel-routes

camel.metrics.enable-route-policy=true
camel.metrics.enable-message-history=true
camel.metrics.enable-exchange-event-notifier=true