spring.application.name=aisi-camel-routes
server.port=8085


camel.springboot.main-run-controller=true
camel.springboot.name=NetflixApiCamelContext
camel.springboot.stream-caching-enabled=true

management.endpoints.web.exposure.include=health,info,camelroutes
management.endpoint.health.show-details=always

logging.level.hr.algebra=DEBUG
logging.level.org.apache.camel=INFO

spring.jackson.serialization.indent-output=true